# Generated by Django 3.2 on 2024-09-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessnumbers',
            name='lottos',
            field=models.CharField(default='[1, 2, 3, 4, 5, 6]', max_length=255),
        ),
    ]
